### ISSUE TITLE
why call the test directory "tests" instead of "test"?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ip2#14]
Everyone else has a src and a test directory. That's the normal.

We have that sometimes, but sometimes we use "sorc" and sometimes "tests".

If we stick to the convention, life gets easier. Can we change the tests directory to the more standard name "test"?

**Comment by edwardhartnett** [comment]
OK, I spoke too soon here, "test" is what autotools uses by default, but "tests" is what CMake uses, and it is what we used everywhere else. So let's stay with "tests" for our tests.

We will change sorc to src where we find it.

**Comment by kgerheiser** [comment]
I reverted it again. We can close this then?
