### ISSUE TITLE
What is a negative grid number?

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-ip2#20]
I've been combining the two ip libraries and there's a case where I'm not sure what to do. There are several references to `IF(IGDTNUMO.GE.0) THEN`. Can IGDTNUM be a negative number? Does that mean it's a partial grid or something?

@GeorgeGayno-NOAA

**Comment by GeorgeGayno-NOAA** [comment]
It typically means interpolation to random station points.
